config/routes.rb
Rails4MysqlMongo::Application.routes.draw do
  
  
  match "policies/search_and_filter" => "policies#index", :via => [:get, :post], :as => :search_policies
  resources :policies do
    collection do
      post :batch
      get  :treeview
    end
    member do
      post :treeview_update
    end
  end

  match ':model_sym/select_fields' => 'beautiful#select_fields', :via => [:get, :post]

  resources :movies

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  get "home/index"

  

end

app/views/layouts/_beautiful_menu.html.erb
<!-- Beautiful Scaffold Menu Do Not Touch This -->
      <li class="<%= "active" if params[:controller] == "policies" %>">
        <%= link_to t('app.models.policy.bs_caption_plural', :default => 'policy').capitalize, policies_path %>
      </li>

app/views/layouts/_form_habtm_tag.html.erb
<%#=
  render :partial => "layouts/form_habtm_tag", :locals => {
    :model_class => @product,
    :model_name => "product",
    :plural_model_name => "products",
    :linked_model_name => "tag",
    :plural_linked_model_name => "tags",
    :namespace_bs => "admin",
    :field_to_search_for_linked_model => "name",
    :f => f
  }
  # Example to put in a _form.html.erb
%>
<% path_namespace = '/' + namespace_bs if not namespace_bs.blank? %>

<div class="control-group">
    <%= f.label plural_linked_model_name.to_sym, t(plural_linked_model_name.to_sym, :default => plural_linked_model_name.capitalize), :class => "control-label" %>
    <div class="controls">
        <ul class="bs-tagit" id="<%= model_name %>_<%= linked_model_name %>_ids" name="<%= model_name %>[<%= linked_model_name %>_ids][]" data-url="<%= path_namespace %>/<%= plural_linked_model_name %>/search_and_filter.json" data-param="q[<%= field_to_search_for_linked_model %>_cont]" data-result="caption">
          <% begin %>
            <% for elt in model_class.send(plural_linked_model_name) %>
            <li data-value="<%= elt.id %>"><%= elt.caption %></li>
            <% end %>
          <% rescue %>
          <% end %>
        </ul>
    </div>
</div>

app/views/layouts/_left_panel.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">FAQ <small>Frequently Asked Questions</small></h1>

      <ul class="breadcrumb">
        <li><a href="index.html">Home</a> <span class="divider">/</span></li>
        <li class="active">FAQ</li>
      </ul>
    </div>

  </div>

  <div class="row">

    <div class="col-lg-12">

      <div class="accordion" id="accordion2">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
              Collapsible Group Item #1
            </a>
          </div>
          <div id="collapseOne" class="accordion-body collapse in">
            <div class="accordion-inner">
              Anim pariatur cliche..ritesh.
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
              Collapsible Group Item #2
            </a>
          </div>
          <div id="collapseTwo" class="accordion-body collapse">
            <div class="accordion-inner">
              Anim pariatur cliche.. kumar.
            </div>
          </div>
        </div>

        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
              Collapsible Group Item #2
            </a>
          </div>
          <div id="collapseThree" class="accordion-body collapse">
            <div class="accordion-inner">
              Anim pariatur cliche.. kaddress.
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div><!-- /.container -->

<div class="container">

  <hr>

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Company 2013</p>
      </div>
    </div>
  </footer>

</div><!-- /.container -->

app/views/layouts/_mass_inserting.html.erb
<% formparams = [] %>
<% if not namespace.blank? then %>
  <% formparams << namespace %>
<% end %>
<% formparams << model_name.camelize.constantize.new %>
<%= form_for formparams, :method => :post, :html => { :class => "well well-small form-horizontal mass-inserting #{(params[:mass_inserting] ? 'setfocus' : '')}" } do |f| %>
  <%= hidden_field_tag :mass_inserting, true %>
  <% for col in model_columns %>
    <div <%= visible_column(model_name, col, 'inline') %> class="col-<%= col %>">
      <%=
        ar = model_name.camelize.constantize.columns_hash[col]
        if not ar.nil? then
          case ar.type
          when :integer then
            if col =~ /.*_id/ then
              f.collection_select((col).to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q][col + "_eq"].to_i rescue '' end) }, { :class => "input-small" })
            else
              f.text_field(col.to_sym, :class => "input-small", :placeholder => col.capitalize)
            end
          when :boolean then
            (
            "<label class='bs-label-ib'>#{f.check_box(col.to_sym, {}, true, false)}#{col.capitalize}</label>".html_safe
            )
          else
            f.text_field(col.to_sym, :class => "input-small", :placeholder => col.capitalize)
          end
        else
          f.collection_select((col + '_id').to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q][col + "_id_eq"].to_i rescue '' end) }, { :class => "input-small" })
        end
      %>
    </div>
  <% end %>
  <div style="display:inline;">
    <%= f.submit t(:create, :default => "Create"), :class => "btn" %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modal_columns.html.erb
<div class="modal hide" id="modal-columns">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><%= t(:select_columns, :default => "Select Columns") %></h3>
  </div>
  <div class="modal-body">
    <% for field in model_columns %>
      <label class="checkbox">
        <input type="checkbox" name="field[]" value="<%= field %>" <%= "checked" if session[:fields][model_name.to_sym].include?(field) %>> <%= t("app.models.#{model_name}.bs_attributes.#{field}", :default => field.capitalize) %>
      </label><br />
    <% end %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-primary" id="filter-columns" data-url="/<%= model_name %>/select_fields">Ok</button>
    <button type="button" class="btn" id="cancel-filter-columns"><%= t(:cancel, :default => "Cancel") %></button>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">


<%= link_to APPLICATION_NAME, root_path, :class => 'brand' %>
<div class="nav-collapse collapse">
<ul class="nav nav-pills">
  <% if user_signed_in? %>
      <li class="<%= get_link_image('policies') %>"><%= link_to 'Policy', policies_path %></li>
    <li class="<%= get_link_image('registrations','edit') %>"><%= link_to 'Edit account', edit_user_registration_path %></li>
    <% if current_user.has_role? :admin %>
      <li><%= link_to 'Admin', users_path %></li>
    <% end %>
  <% else %>
    <li class="<%= get_link_image('registrations','new') %>"><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
  <!--<li><%#= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>-->
  <!--<li><%#= controller_name %><%#= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>-->


  <% if user_signed_in? %>
      <li class="<%= get_link_image('users','sign_up') %>"><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
      <li class="<%= get_link_image('sessions','new') %>"><%= link_to 'Login', new_user_session_path %></li>
  <% end %>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a href="#">FAQ</a></li>
      <li><a href="#">Blog</a></li>
      <li><a href="#">Forum</a></li>
      <li class="divider"></li>
      <li class="nav-header">Personal Settings</li>
      <li><a href="#">My Settings</a></li>
      <li><a href="#">One more separated link</a></li>
    </ul>
  </li>
</ul>


  <% unless user_signed_in? || (controller_name == 'sessions' && controller.action_name == 'new') %>

  <%= simple_form_for @user, :url => session_path(@user), :html => {:class => 'navbar-form pull-right' } do |f| %>
    <input class="span2" type="text" placeholder="Email" name="user[email]">
    <input class="span2" type="password" placeholder="Password" name="user[password]">

      <!--<input type="checkbox" name="user[remember_me]" />-->
      <%#= f.input :remember_me, :as => :boolean, :wrapper => :inline_checkbox, :class=>"span2"  %>
    <button type="submit" class="btn btn-success">Sign in</button>
  <!--</form>-->
  <% end %>
  <% end %>

</div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : APPLICATION_NAME %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : APPLICATION_NAME %>">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>

</head>
<body class="<%= controller_name %> <%= action_name %>" style="background: none repeat scroll 0 0 rgb(200,200,200);">

<%= render 'layouts/navigation' %>

<%#= render 'layouts/left_panel' %>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span12">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>
</body>
</html>

app/views/layouts/beautiful_layout.html.erb
<!DOCTYPE html>
<html lang="<%= (I18n.locale || I18n.default_locale) %>">
<head>
  <meta charset="utf-8">
  <title>Beautiful Scaffold</title>

  <meta name="description" content="Beautiful Scaffold">
  <meta name="author" content="You or me Sylvain Claudel (http://blog.escarworld.com)">

  <%= stylesheet_link_tag "application-bs" %>
  <%= javascript_include_tag "application-bs" %>

  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body class="<%= controller_name %> <%= action_name %>" style="background: none repeat scroll 0 0 rgb(200,200,200);">

<%= render 'layouts/navigation' %>

<div class="container-fluid">
  <div class="row-fluid">
    <!--<div class="span2">-->
      <!--<ul class="nav nav-list well">-->
        <!--<li class="nav-header">-->
          <!--Menu-->
        <!--</li>-->
        <!--<%#= render :partial => "layouts/beautiful_menu" %>-->
      <!--</ul>-->
    <!--</div>-->
    <div class="span12">
      <% if not flash[:notice].blank? then %>
          <div class="alert alert-info">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <h4 class="alert-heading">Info : </h4>
            <%= flash[:notice] %>
          </div>
      <% end %>
      <% if not flash[:error].blank? then %>
          <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <h4 class="alert-heading">Error : </h4>
            <%= flash[:error] %>
          </div>
      <% end %>
      <!--<div style="background:none repeat scroll 0% 0% rgb(11, 42, 73);padding: 10px;color: white;">-->
      <div style="background:none repeat scroll 0 0 rgb(255,255,255);padding: 10px;">
          <%= yield %>
      </div>
    </div>
  </div>
</div>

<div class="loader" style="display:none">
  <div class="circle"></div>
  <div class="circle1"></div>
</div>
<%= render 'shared/footer' %>
<!-- Beautiful_scaffold - Modal - Do not remove -->

<script type="text/javascript">
    <% if not @opened_modal.blank? then %>
    $('<%= @opened_modal %>').modal('show');
    <% end %>
</script>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : APPLICATION_NAME %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : APPLICATION_NAME %>">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
        <%= render 'layouts/navigation' %>
              <%= yield %>
  <%= render 'shared/footer' %>

  </body>
</html>