config/routes.rb
Rails4MysqlMongo::Application.routes.draw do
  
  
  match "policies/search_and_filter" => "policies#index", :via => [:get, :post], :as => :search_policies
  resources :policies do
    collection do
      post :batch
      get  :treeview
    end
    member do
      post :treeview_update
    end
  end

  match ':model_sym/select_fields' => 'beautiful#select_fields', :via => [:get, :post]

  resources :movies

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  get "home/index"

  

end

app/models/policy.rb
class Policy < ActiveRecord::Base
  scope :sorting, lambda{ |options|
    attribute = options[:attribute]
    direction = options[:sorting]

    attribute ||= "id"
    direction ||= "DESC"

    order("#{attribute} #{direction}")
  }

  include BeautifulScaffoldModule
  before_save :fulltext_field_processing

  validates_presence_of :name

  # You can OVERRIDE this method used in model form and search form (in belongs_to relation)
  def caption
    (self["name"] || self["label"] || self["description"] || "##{id}")
  end

  def fulltext_field_processing
    # You can preparse with own things here
    generate_fulltext_field(["description"])
  end

  def self.permitted_attributes
    return :name,:description,:company,:address,:start_date,:end_date,:status,:amount,:interest_rate,:time_period
  end
end

app/controllers/policies_controller.rb
# encoding : utf-8
class PoliciesController < BeautifulController
  before_filter :authenticate_user!
  before_filter :load_policy, :only => [:show, :edit, :update, :destroy]

  # Uncomment for check abilities with CanCan
  #authorize_resource

  def index
    session[:fields] ||= {}
    session[:fields][:policy] ||= (Policy.columns.map(&:name) - ["id"])[0..4]
    do_select_fields(:policy)
    do_sort_and_paginate(:policy)
    
    @q = Policy.search(
      params[:q]
    )

    @policy_scope = @q.result(
      :distinct => true
    ).sorting(
      params[:sorting]
    )
    
    @policy_scope_for_scope = @policy_scope.dup
    
    unless params[:scope].blank?
      @policy_scope = @policy_scope.send(params[:scope])
    end
    
    @policies = @policy_scope.paginate(
      :page => params[:page],
      :per_page => 20
    ).to_a

    respond_to do |format|
      format.html{
        render
      }
      format.json{
        render :json => @policy_scope.to_a
      }
      format.csv{
        require 'csv'
        csvstr = CSV.generate do |csv|
          csv << Policy.attribute_names
          @policy_scope.to_a.each{ |o|
            csv << Policy.attribute_names.map{ |a| o[a] }
          }
        end 
        render :text => csvstr
      }
      format.xml{ 
        render :xml => @policy_scope.to_a
      }             
      format.pdf{
        pdfcontent = PdfReport.new.to_pdf(Policy,@policy_scope)
        send_data pdfcontent
      }
    end
  end

  def show
    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @policy }
    end
  end

  def new
    @policy = Policy.new

    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @policy }
    end
  end

  def edit
    
  end

  def create
    @policy = Policy.create(params_for_model)

    respond_to do |format|
      if @policy.save
        format.html {
          if params[:mass_inserting] then
            redirect_to policies_path(:mass_inserting => true)
          else
            redirect_to policy_path(@policy), :flash => { :notice => t(:create_success, :model => "Policy") }
          end
        }
        format.json { render :json => @policy, :status => :created, :location => @policy }
      else
        format.html {
          if params[:mass_inserting] then
            redirect_to policies_path(:mass_inserting => true), :flash => { :error => @policy.errors.messages }
          else
            render :action => "new"
          end
        }
        format.json { render :json => @policy.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @policy.update_attributes(params_for_model)
        format.html { redirect_to policy_path(@policy), :flash => { :notice => t(:update_success, :model => "Policy") }}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @policy.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @policy.destroy

    respond_to do |format|
      format.html { redirect_to policies_url }
      format.json { head :ok }
    end
  end

  def batch
    attr_or_method, value = params[:actionprocess].split(".")

    @policies = []    
    
    Policy.transaction do
      if params[:checkallelt] == "all" then
        # Selected with filter and search
        do_sort_and_paginate(:policy)

        @policies = Policy.search(
          params[:q]
        ).result(
          :distinct => true
        )
      else
        # Selected elements
        @policies = Policy.find(params[:ids].to_a)
      end

      @policies.each{ |policy|
        if not Policy.columns_hash[attr_or_method].nil? and
               Policy.columns_hash[attr_or_method].type == :boolean then
         policy.update_attribute(attr_or_method, boolean(value))
         policy.save
        else
          case attr_or_method
          # Set here your own batch processing
          # policy.save
          when "destroy" then
            policy.destroy
          end
        end
      }
    end
    
    redirect_to :back
  end

  def treeview

  end

  def treeview_update
    modelclass = Policy
    foreignkey = :policy_id

    render :nothing => true, :status => (update_treeview(modelclass, foreignkey) ? 200 : 500)
  end
  
  private 
  
  def load_policy
    @policy = Policy.find(params[:id])
  end

  def params_for_model
    params.require(:policy).permit(Policy.permitted_attributes)
  end
end

app/helpers/policies_helper.rb
# encoding : utf-8
require "beautiful_helper"
module PoliciesHelper
end

app/views/policies/_form.html.erb
<%= simple_form_for(@policy, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

      <ul>
        <% @policy.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %>
      </ul>
    </div>
  <% end %>
      <div class="control-group">
      <%= f.label :name, t('app.models.policy.bs_attributes.name', :default => 'name').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, t('app.models.policy.bs_attributes.description', :default => 'description').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :description, :class => "richtext-editor" %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inlineCheckboxes"></label>
      <div class="controls">
        
          <% hashradio = {:id => "description-bbcode", :class => "select-richtext", 'data-editor' => 'markItUpPolicy_description', 'data-spleditor' => 'policy_description' } %>
          <% hashradio[:checked] = "checked" if @policy.description_typetext == "bbcode" %>
          <label for="description-bbcode" class="label-richtext-type checkbox inline">
            <%= f.radio_button :description_typetext, "bbcode", hashradio  %>
            Bbcode
          </label>
        
          <% hashradio = {:id => "description-html", :class => "select-richtext", 'data-editor' => 'markItUpPolicy_description', 'data-spleditor' => 'policy_description' } %>
          <% hashradio[:checked] = "checked" if @policy.description_typetext == "html" %>
          <label for="description-html" class="label-richtext-type checkbox inline">
            <%= f.radio_button :description_typetext, "html", hashradio  %>
            Html
          </label>
        
          <% hashradio = {:id => "description-text", :class => "select-richtext", 'data-editor' => 'markItUpPolicy_description', 'data-spleditor' => 'policy_description' } %>
          <% hashradio[:checked] = "checked" if @policy.description_typetext == "text" %>
          <label for="description-text" class="label-richtext-type checkbox inline">
            <%= f.radio_button :description_typetext, "text", hashradio  %>
            Text
          </label>
        
          <% hashradio = {:id => "description-wiki", :class => "select-richtext", 'data-editor' => 'markItUpPolicy_description', 'data-spleditor' => 'policy_description' } %>
          <% hashradio[:checked] = "checked" if @policy.description_typetext == "wiki" %>
          <label for="description-wiki" class="label-richtext-type checkbox inline">
            <%= f.radio_button :description_typetext, "wiki", hashradio  %>
            Wiki
          </label>
        
          <% hashradio = {:id => "description-textile", :class => "select-richtext", 'data-editor' => 'markItUpPolicy_description', 'data-spleditor' => 'policy_description' } %>
          <% hashradio[:checked] = "checked" if @policy.description_typetext == "textile" %>
          <label for="description-textile" class="label-richtext-type checkbox inline">
            <%= f.radio_button :description_typetext, "textile", hashradio  %>
            Textile
          </label>
        
          <% hashradio = {:id => "description-markdown", :class => "select-richtext", 'data-editor' => 'markItUpPolicy_description', 'data-spleditor' => 'policy_description' } %>
          <% hashradio[:checked] = "checked" if @policy.description_typetext == "markdown" %>
          <label for="description-markdown" class="label-richtext-type checkbox inline">
            <%= f.radio_button :description_typetext, "markdown", hashradio  %>
            Markdown
          </label>
        
      </div>
    </div>

    <% rttype = @policy.description_typetext.to_s %>
    <% if not rttype.blank? then %>
    <script language="javascript">
      $(document).ready(function(){
        $('#policy_description').markItUp(my<%= rttype.capitalize %>Settings);
        $('#markItUpPolicy_description').addClass('<%= rttype.downcase %>');
      });
    </script>
    <% end %>
    <div class="control-group">
      <%= f.label :company, t('app.models.policy.bs_attributes.company', :default => 'company').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :company %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, t('app.models.policy.bs_attributes.address', :default => 'address').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :address, :rows => 5 %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :start_date, t('app.models.policy.bs_attributes.start_date', :default => 'start_date').capitalize, :class => "control-label" %>
      <div class="controls">
        <div class="input-append">
          <%= f.text_field :start_date %><span class="add-on"><i class="icon-calendar"></i></span>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :end_date, t('app.models.policy.bs_attributes.end_date', :default => 'end_date').capitalize, :class => "control-label" %>
      <div class="controls">
        <div class="input-append">
          <%= f.text_field :end_date %><span class="add-on"><i class="icon-calendar"></i></span>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :status, t('app.models.policy.bs_attributes.status', :default => 'status').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :status %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :amount, t('app.models.policy.bs_attributes.amount', :default => 'amount').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :amount %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :interest_rate, t('app.models.policy.bs_attributes.interest_rate', :default => 'interest_rate').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :interest_rate %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :time_period, t('app.models.policy.bs_attributes.time_period', :default => 'time_period').capitalize, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :time_period %>
      </div>
    </div>
<!-- Beautiful_scaffold - AddField - Do not remove -->
  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/policies/edit.html.erb
<h2><%= t(:editing, :default => 'Editing') %> <%= t('app.models.policy.bs_caption', :default => 'policy') %></h2>

<%= render 'form' %>

<%= link_to t(:back, :default => "Back"), policies_path, :class => "btn" %>

app/views/policies/index.html.erb
<h2><%= t(:listing, :default => "Listing") %> <%= t('app.models.policy.bs_caption_plural', :default => 'policy') %></h2>

<p>
  <%= link_to '<i class="icon-plus"></i> '.html_safe + t(:new, :default => "New") + ' ' + t('app.models.policy.bs_caption', :default => 'policy'), new_policy_path, :class => "btn" %>
  <% if Policy.columns.map(&:name).include?("policy_id") then %>
    <%= link_to '<i class="icon-folder-close"></i> '.html_safe + t(:treeview, :default => "Treeview") + ' ' + t('app.models.policy.bs_caption', :default => 'policy'), treeview_policies_path, :class => "btn" %>
  <% end %>
</p>

<%= render :partial => "layouts/mass_inserting", :locals => { :namespace => '', :model_name => 'policy', :model_columns => ['name','description','company','address','start_date','end_date','status','amount','interest_rate','time_period'] } %>

<%# Set your scopes below (string in array) %>
<% scopes = [] %>
<% if not scopes.blank? then %>
<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to "All (#{@policy_scope_for_scope.count})", policies_path(:scope => ""), :class => "btn #{((session[:scope][:policy].to_s == '') ? 'active' : '')}" %>
    <% for scope in scopes %>
    <%= link_to "#{scope} (#{@policy_scope_for_scope.send(scope).count})", policies_path(:scope => scope), :class => "btn #{((session[:scope][:policy].to_s == scope) ? 'active' : '')}" %>
    <% end %>
  </div>
</div>
<% end %>

<div class="row-fluid">
  <div class="span9">
    <%= form_tag  batch_policies_path, :class => "form-inline" do %>
      <div class="well well-small">
        <label class="control-label" for="select01"><%= t(:batch, :default => "Batch") %></label>

        <select id="select01" name="actionprocess">
          <option value="destroy"><%= t(:destroy, :default => "Destroy") %></option>
          
          <!-- Beautiful_scaffold - AddField - Batch - Do not remove -->
        </select>
        <button class="btn" type="submit"><i class="icon-ok"></i> <%= t(:process, :default => "Process") %></button>
      </div>

      <%= render :partial => "layouts/modal_columns", :locals => { :model_name => "policy", :model_columns => ['name','description','company','address','start_date','end_date','status','amount','interest_rate','time_period','created_at','updated_at'] } %>

      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th>
              <a class="" data-toggle="modal" href="#modal-columns" title="<%= t(:select_columns, :default => "Select Columns") %>" ><i class="icon-th-list"></i></a>
            </th>
            <th>
              <%= check_box_tag :checkall, '' %>
            </th>
            <th <%= visible_column("policy", "name") %> class="col-name">
  <%= sorting_header("policy", "name", "") %>
</th>
<th <%= visible_column("policy", "description") %> class="col-description">
  <%= sorting_header("policy", "description", "") %>
</th>
<th <%= visible_column("policy", "company") %> class="col-company">
  <%= sorting_header("policy", "company", "") %>
</th>
<th <%= visible_column("policy", "address") %> class="col-address">
  <%= sorting_header("policy", "address", "") %>
</th>
<th <%= visible_column("policy", "start_date") %> class="col-start_date">
  <%= sorting_header("policy", "start_date", "") %>
</th>
<th <%= visible_column("policy", "end_date") %> class="col-end_date">
  <%= sorting_header("policy", "end_date", "") %>
</th>
<th <%= visible_column("policy", "status") %> class="col-status">
  <%= sorting_header("policy", "status", "") %>
</th>
<th <%= visible_column("policy", "amount") %> class="col-amount">
  <%= sorting_header("policy", "amount", "") %>
</th>
<th <%= visible_column("policy", "interest_rate") %> class="col-interest_rate">
  <%= sorting_header("policy", "interest_rate", "") %>
</th>
<th <%= visible_column("policy", "time_period") %> class="col-time_period">
  <%= sorting_header("policy", "time_period", "") %>
</th>

            <!-- Beautiful_scaffold - AddField - Header - Do not remove -->
            <th <%= visible_column("policy", "created_at") %> class="col-created_at">
              <%= sorting_header("policy", "created_at", "") %>
            </th>
            <th <%= visible_column("policy", "updated_at") %> class="col-updated_at">
              <%= sorting_header("policy", "updated_at", "") %>
            </th>
            <th colspan="3">
              <label class="checkbox">
                <%= check_box_tag :checkallelt, 'all' %>
                <%= pluralize(@policy_scope.count, "policy") %>
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @policies.each do |policy| %>
          <tr class="line-<%= cycle("1","2") %>">
            <td><%= policy.id %></td>
            <td><%= check_box_tag "ids[]",policy.id, false, :class => 'cbbatch' %></td>
              <td <%= visible_column("policy", "name") %> class="col-name <%= align_attribute("string") %>">
      <%= policy.name %>
  </td>
  <td <%= visible_column("policy", "description") %> class="col-description <%= align_attribute("richtext") %>">
      <%= truncate(policy.description_fulltext, :length => 30) %>
  </td>
  <td <%= visible_column("policy", "company") %> class="col-company <%= align_attribute("string") %>">
      <%= policy.company %>
  </td>
  <td <%= visible_column("policy", "address") %> class="col-address <%= align_attribute("text") %>">
      <%= policy.address %>
  </td>
  <td <%= visible_column("policy", "start_date") %> class="col-start_date <%= align_attribute("date") %>">
      <%= policy.start_date %>
  </td>
  <td <%= visible_column("policy", "end_date") %> class="col-end_date <%= align_attribute("date") %>">
      <%= policy.end_date %>
  </td>
  <td <%= visible_column("policy", "status") %> class="col-status <%= align_attribute("string") %>">
      <%= policy.status %>
  </td>
  <td <%= visible_column("policy", "amount") %> class="col-amount <%= align_attribute("float") %>">
      <%= policy.amount %>
  </td>
  <td <%= visible_column("policy", "interest_rate") %> class="col-interest_rate <%= align_attribute("float") %>">
      <%= policy.interest_rate %>
  </td>
  <td <%= visible_column("policy", "time_period") %> class="col-time_period <%= align_attribute("string") %>">
      <%= policy.time_period %>
  </td>
<!-- Beautiful_scaffold - AddField - Column - Do not remove -->
            <td <%= visible_column("policy", "created_at") %> class="col-created_at <%= align_attribute("datetime") %>">
              <%= l(policy.created_at, :format => :long) %>
            </td>
            <td <%= visible_column("policy", "updated_at") %> class="col-updated_at <%= align_attribute("datetime") %>">
              <%= l(policy.updated_at, :format => :long) %>
            </td>
            <td><%= link_to '<i class="icon-search"></i>'.html_safe, policy_path(policy), :title => t(:show, :default => "Show") %></td>
            <td><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_policy_path(policy), :title => t(:edit, :default => "Edit") %></td>
            <td><%= link_to '<i class="icon-remove"></i>'.html_safe, policy_path(policy), :data => { :confirm => t(:are_you_sure, :default => "Are you sure?") }, :method => :delete, :title => t(:destroy, :default => "Destroy") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="btn-toolbar">
        <div class="btn-group">
          <% clean_params %>
          <%= will_paginate @policies,
                  :inner_window => 0,
                  :outer_window => 0,
                  :previous_label => t(:prev, :default => "Previous"),
                  :next_label => t(:next, :default => "Next") %>

        </div>
        <div class="btn-group pull-right">
          <%= link_to '<i class="icon-download"></i> CSV'.html_safe,  policies_path(:format => :csv), :class => "btn" %>
          <%= link_to '<i class="icon-download"></i> XML'.html_safe,  policies_path(:format => :xml), :class => "btn" %>
          <%= link_to '<i class="icon-download"></i> JSON'.html_safe, policies_path(:format => :json), :class => "btn" %>
          <%= link_to '<i class="icon-download"></i> PDF'.html_safe,  policies_path(:format => :pdf), :class => "btn" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="span3">
    <%= search_form_for @q, :url => search_policies_path, :html => { :class => "well well-small" }, :method => :post do |f| %>
        <%= ransack_field("policy", "name", f, "Name") %>
  <%= ransack_field("policy", "description_fulltext", f, "Description") %>
  <%= ransack_field("policy", "company", f, "Company") %>
  <%= ransack_field("policy", "address", f, "Address") %>
  <%= ransack_field("policy", "start_date", f, "Start_date (dd/mm/yyyy)") %>
  <%= ransack_field("policy", "end_date", f, "End_date (dd/mm/yyyy)") %>
  <%= ransack_field("policy", "status", f, "Status") %>
  <%= ransack_field("policy", "amount", f, "Amount") %>
  <%= ransack_field("policy", "interest_rate", f, "Interest_rate") %>
  <%= ransack_field("policy", "time_period", f, "Time_period") %>

        <%= ransack_field("policy", "created_at", f, "Created At (dd/mm/yyyy)") %>
  <%= ransack_field("policy", "updated_at", f, "Updated At (dd/mm/yyyy)") %>
  <%= ransack_field("policy", "id", f, "Id") %>

      <!-- Beautiful_scaffold - AddField - Search - Do not remove -->
      <%= f.submit t(:filter, :default => "Filter"), :class => "btn btn-primary" %>
      <%= link_to  t(:cancel, :default => "Cancel"), policies_path(:nosearch => "ok"), :class => "btn" %>
    <% end %>
  </div>
</div>




<script type="text/javascript">
    $('#filter-columns').on('click', function(){
        var return_json = [];
        $.each($('input[name^="field"]:checked'), function(index, value) {
            return_json.push($(value).val());
        });
        $.ajax({
            url: '/policy/select_fields',
            data: { 'fields' : return_json },
            success: function(data) {
                $('table.table th[class^="col"], table.table td[class^="col"]').css('display', 'none');
                $.each(return_json, function(index, value) {
                    $('table.table th.col-' + value + ', table.table td.col-' + value).css('display', 'table-cell');
                });
                $('#modal-columns').modal('hide');
            }
        });
        return false;
    });
    $('#cancel-filter-columns').on('click', function(){
        $('#modal-columns').modal('hide');
        return false;
    });
</script>

app/views/policies/new.html.erb
<h2><%= t(:new, :default => 'New') %> <%= t('app.models.policy.bs_caption', :default => 'policy') %></h2>

<%= render 'form' %>

<%= link_to t(:back, :default => "Back"), policies_path, :class => "btn" %>

app/views/policies/show.html.erb
<h2><%= t(:show, :default => "Show") %> <%= t('app.models.policy.bs_caption', :default => 'policy') %></h2>

  <p>
    <b><%= t('app.models.policy.bs_attributes.name', :default => 'name') %>:</b>
      <%= @policy.name %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.description', :default => 'description') %>:</b>
      <%= @policy.description %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.company', :default => 'company') %>:</b>
      <%= @policy.company %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.address', :default => 'address') %>:</b>
      <%= @policy.address %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.start_date', :default => 'start_date') %>:</b>
      <%= @policy.start_date %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.end_date', :default => 'end_date') %>:</b>
      <%= @policy.end_date %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.status', :default => 'status') %>:</b>
      <%= @policy.status %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.amount', :default => 'amount') %>:</b>
      <%= @policy.amount %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.interest_rate', :default => 'interest_rate') %>:</b>
      <%= @policy.interest_rate %>
  </p>
  <p>
    <b><%= t('app.models.policy.bs_attributes.time_period', :default => 'time_period') %>:</b>
      <%= @policy.time_period %>
  </p>

<!-- Beautiful_scaffold - AddField - Field - Do not remove -->

<%= link_to t(:edit, :default => "Edit"), edit_policy_path(@policy), :class => "btn" %>
<%= link_to t(:back, :default => "Back"), policies_path, :class => "btn" %>

app/views/policies/treeview.html.erb
<h2><%= t(:treeview, :default => 'Treeview') %> <%= t('app.models.policy.bs_caption', :default => 'policy') %></h2>

<%
namespace_for_url = ""
plural_model_name = "policies"
model_name        = "policy"
opened_node       = Policy.select(:id).all.map{ |g| "'treeelt_" + g.id.to_s + "'" }.join(',').html_safe
%>

<div id="treeview" data-model="<%= model_name %>" data-url="/<%= namespace_for_url %><%= plural_model_name %>/" data-opened="[<%= opened_node %>]">
  <ul>
    <% Policy.transaction do %>
    <% ar = Policy.where(:policy_id => nil) %>
    <% ar = ar.order("position") if Policy.column_names.include?("position") %>
      <% for g in ar.all %>
        <%= build_treeview(g, 'policies') %>
      <% end %>
    <% end %>
  </ul>
</div>